# Generated by Django 4.2.16 on 2026-08-31 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章点赞',
                'verbose_name_plural': '文章点赞',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(max_length=1000, verbose_name='项目描述')),
                ('url', models.URLField(blank=True, verbose_name='项目链接')),
                ('repo_url', models.URLField(blank=True, verbose_name='仓库链接')),
                ('tech_stack', models.CharField(blank=True, help_text='逗号分隔，如：React,Django,MySQL', max_length=200, verbose_name='技术栈')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='项目封面')),
                ('is_featured', models.BooleanField(default=False, verbose_name='精选')),
                ('order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='内容')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '杂谈',
                'verbose_name_plural': '杂谈',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TalkLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '杂谈点赞',
                'verbose_name_plural': '杂谈点赞',
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-is_top', '-created_at'], name='blog_articl_is_top_a1ec3d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', '-created_at'], name='blog_articl_categor_69d837_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', '-created_at'], name='blog_articl_author__524cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['views'], name='blog_articl_views_0a8706_idx'),
        ),
        migrations.AddField(
            model_name='talklike',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.talk', verbose_name='杂谈'),
        ),
        migrations.AddField(
            model_name='talklike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talk_likes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='talk',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.article', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddConstraint(
            model_name='talklike',
            constraint=models.UniqueConstraint(fields=('talk', 'user'), name='uniq_talk_like_user'),
        ),
        migrations.AddConstraint(
            model_name='talklike',
            constraint=models.UniqueConstraint(fields=('talk', 'ip_address'), name='uniq_talk_like_ip'),
        ),
        migrations.AddIndex(
            model_name='talk',
            index=models.Index(fields=['-created_at'], name='blog_talk_created_6e8309_idx'),
        ),
        migrations.AddConstraint(
            model_name='articlelike',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='uniq_article_like_user'),
        ),
        migrations.AddConstraint(
            model_name='articlelike',
            constraint=models.UniqueConstraint(fields=('article', 'ip_address'), name='uniq_article_like_ip'),
        ),
    ]
