# Generated by Django 4.2.16 on 2026-09-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlelike_project_talk_talklike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
